services:
    - docker

env:
  global:
    - IMAGE=qgis/qgis

  matrix:
    - QGIS_VERSION_TAG=latest

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - pip install --upgrade pip
  - pip install --upgrade pylint
  - pip install --upgrade pycodestyle
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "cd /tests_directory && export PYTHONPATH=$(pwd):$PYTHONPATH"
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh qgis_resource_sharing"

script:
  - docker exec -it qgis-testing-environment sh -c "cd /tests_directory && qgis_testrunner.sh test_suite.test_qgis3"

sudo: false
