language: python

sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq -y update

env:
#  - QGIS_REPO=http://qgis.org/debian-ltr (testing module is not there)
  - QGIS_REPO=http://qgis.org/debian-nightly-release

install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ${QGIS_REPO}
  - sudo apt-get update
  - sudo apt-get install -y --force-yes qgis python-qgis xvfb
  - sudo pip install nose2

script:
  - export PATH=/usr/bin:$PATH
  - xvfb-run nose2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f55e2fa1a258c0906e3b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

