blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://qgis-contribution.github.io/QGIS-ResourceSharing/
    about: Please read carefully the documentation before to submit an issue.
