name: Doc build and deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/*/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'docs/*/**'

env:
  PYTHON_VERSION: 3.7

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/documentation.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -U -r requirements/documentation.txt

    - name: Build doc using Sphinx
      run: sphinx-build -b html docs docs/_build/html

    # - name: Deploy to GitHub Pages
    #   run: ghp-import --force --no-jekyll --push docs/_build/html
